### ISSUE TITLE
Error after start

### ISSUE THREAD

**Issue by mateuslecchi** [bearlike/REMS-For-Organisations#54]
I had error like the image in various instances, when I try to log in or search. I've done the setup following the readme.
![image](https://user-images.githubusercontent.com/45340326/110567005-977e1280-812f-11eb-9c74-e371bee985f0.png)
![image](https://user-images.githubusercontent.com/45340326/110567050-a795f200-812f-11eb-8912-b64b75e58b0b.png)

**Comment by bearlike** [comment]
Can you paste the complete logs here? And, is the database with all tables created?

**Comment by mateuslecchi** [comment]
I find that was a error in my server, I was able to solve this and now I'm stuck in a blank screen after login, some error with validate.php. 
![image](https://user-images.githubusercontent.com/45340326/110633610-bb6d4280-8187-11eb-88b2-163f95648e57.png)
I've create de MainDB, but I dont find the schemas for the others DBs.

The system is hoted here [https://mateuslecchi.com.br/rems/](https://mateuslecchi.com.br/rems/) 

I cant find the logs in my host dashboard.

**Comment by bearlike** [comment]
1. An `error.log` must have been generated during any runtime errors, find them and paste them here. Usually located in `/var/log/apache2`, if PHP is an apache2 module
2. `validate.php` does not require any other schemas than `MainDB`. 
3. Can you also let me know what PHP is your server running?

**Comment by mateuslecchi** [comment]
Thank you for the attention, I realize that is a problem with my server, because in a test running the system in a local server with xampp and it works fine.
