### ISSUE TITLE
Blank screen appears after deploying using Docker

### ISSUE THREAD

**Issue by dhanuhammer** [bearlike/REMS-For-Organisations#58]
Hello

I deployed this application on Oracle VPS using Docker as per your steps, and configured everything as much as possible as per your README . I was able to get the application running but when I login with the default credentials, I get a blank screen.

I dont know how to proceed, Kindly help me out
Thank you

**Comment by bearlike** [comment]
I understand. Can you restarting the containers? Sometimes, the config files could be faulty or databases could be booting in the backtground.

**Comment by bearlike** [comment]
Closing stale issue.
