### ISSUE TITLE
[BUG] System not working

### ISSUE THREAD

**Issue by sketchuprzr** [bearlike/REMS-For-Organisations#60]
I installed as instructed.

The files are hosted on the server, and seem to be working.

But it's not working.
e.g. In the Certificate Generator page, when I import a list, the link does not work.

The imported and created certificates do not contain phrases such as name or school.

The Certificates page does not contain previously created certificate lists.

"Bulk Mailer" , "Update Mailing List" , "Form Generator" , "Link Shortner" , "View Registration"

These pages never work. When I click it, it enters the "login" page.

There is static data on the Dashboard page.

Are you sure the system is working?

**Comment by bearlike** [comment]
Can you share the logs from your Apache Server? Can you also describe your setup for us better understand the setup. Also, please verify if the database setup is completed as recommended.

**Comment by sketchuprzr** [comment]
We do not have a detailed explanation for installation. 
We installed the system with a web developer and tried to test it, but the system does not work.

Before requesting a detailed report, please prepare a detailed installation instruction.

Ex. It doesn't even say that pdo PHP extensions need to be installed on a server!

We removed it from the server because the system didn't work. Please check your source code description and edit it as a more detailed description. Otherwise, do not request detailed reports from users.

**Comment by bearlike** [comment]
Thank you for letting us know about the missing step in our installation process. But without any logs (or anything), we cannot authenticate the legitimacy of the issue. Moreover, I still believe there must be primitive incomplete installations on your end. 

We have users running the application so if you have discovered any bug, we would greatly appreciate a detailed bug report as it'd help the project.
